"""Initial schema

Revision ID: 99975bc45c5d
Revises: 
Create Date: 2026-08-26 13:52:45.791706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99975bc45c5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcandidate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retailer_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoppinglist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storeskupreference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_retailer_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisonrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shoppinglist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoppinglistitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('must_have', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shoppinglist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchdecision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['productcandidate.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['shoppinglistitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storequote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['comparisonrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['storequote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quoteline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['productcandidate.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['storequote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderreceipt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_total_cents', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderreceipt')
    op.drop_table('quoteline')
    op.drop_table('approval')
    op.drop_table('storequote')
    op.drop_table('matchdecision')
    op.drop_table('shoppinglistitem')
    op.drop_table('comparisonrun')
    op.drop_table('storeskupreference')
    op.drop_table('shoppinglist')
    op.drop_table('productcandidate')
    # ### end Alembic commands ###
